### ISSUE TITLE
`createIndex` and `getIndex`

### ISSUE THREAD

**Issue by justinmchase** [jiawei397/deno_es#2]
Thanks for this library!

I noticed when I first went to use it that its missing the createIndex and getIndex methods, was just hoping you could add those here!

I can just add them to my code since its a fairly simple rest call but it would be a nice addition I think.

Obviously this isn't fully right but here is my workaround:

```ts
import { ajax } from "https://deno.land/x/deno_es@v0.1.0/src/utils/ajax.ts"

export async function createIndex(index: string, mapping: unknown): Promise<unknown> {
  return await ajax({
    url: `http://localhost:9200/${index}`,
    method: 'PUT',
    data: mapping
  });
}
```

And yes you can just infer your indexes from the documents stored in the index some of the time, but not always. Generally you'll end up wanting to strictly define your mappings and some kinds like a percolate always require explicit mappings.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html

**Comment by jiawei397** [comment]
I'm very glad you can use this project. I'll take a look at this API and add it.

**Comment by jiawei397** [comment]
It seems like that you can use like this:
```ts
const createIndex = async () => {
  try {
    const info = await client.indices.create({
      index: "myindex",
      // body: {},
      body: {
        "mappings": {
          "properties": {
            "message": {
              "type": "text",
            },
            "query": {
              "type": "percolator",
            },
          },
        },
      },
    });
    console.log("createIndex success", info);
  } catch (error) {
    console.error(error);
  }
};
```

If you want to getIndex, you can see the `client.indices.stats` that wether meet your needs.

**Comment by justinmchase** [comment]
I see, I thought it was `private` because it lacked a modifier but I see that defaults to `public`.

Also it does seem like the `.get(_id: string)` method to get a document by `_id` is missing?
