### ISSUE TITLE
`client.get` is missing

### ISSUE THREAD

**Issue by justinmchase** [jiawei397/deno_es#5]
It would be nice if there was a simple get by id function

**Comment by jiawei397** [comment]
Thank you for your advice. In this project, I only added some APIs that I currently use in nestjs. If there are any APIs that do not meet your needs, you can fork them and I will merge them. 
I've been busy recently. I may not have enough time to spend on it. I may spend more time dealing with `Mongo`.

Now you can use like this:

```ts
const findById = async () => {
  try {
    const info = await client.get({
      index: "myindex",
      id: "11",
    });
    console.log(info);
  } catch (error) {
    console.error(error);
  }
};
```
